### ISSUE TITLE
Parsing VmtxTable fails for C:\Windows\Fonts\msyi.ttf

### ISSUE THREAD

**Issue by roy-t** [roy-t/TrueType#6]
@wldevries the new addition for the VmtxTable seems to have a bug, with the msyi.ttf font it fails because it tries to read past the end of the stream. 

Can you try to run WindowsFontsTest.ShouldParseWindowsFonts and try to debug the issue? Unfortunately I'm not familiar with the VmtxTable, but for you its fresh in your head 😄 .

**Comment by roy-t** [comment]
It looks like it also happens in `C:\Windows\Fonts\simsunb.ttf`, all other fonts I have installed seem fine. Both are Chinese fonts so maybe its an issue with top->bottom fonts?.

Note that I've just pushed a new version to master, that highlights this issue better.

**Comment by wldevries** [comment]
After adding sanity checks that compares the expected table length and the actual table length there are problems in a lot of fonts. A similar issue occurs in the HmtxTable table.

I suspect the counters are maybe wrong: `VheaTable.NumberOfVMetrics`, `HheaTable.NumberOfHMetrics` and `MaxpTable.NumGlyphs`. At the moment I'm a bit at a loss though. They seem to be read at the correct table offset and in the correct format. Will investigate more later.

**Comment by wldevries** [comment]
I found the problem: I used the `FontReader.Seek` method which seeks from the beginning of the file to skip over reserved space.

https://github.com/roy-t/TrueType/blob/master/RoyT.TrueType/Tables/HheaTable.cs#L28

**Comment by roy-t** [comment]
Ah yes it uses `this.BaseStream.Seek(offset, SeekOrigin.Begin);` feel free to add an overload to `FontReader.Seek` that does a relative seek :)

**Comment by wldevries** [comment]
Can be closed now. Thanks for the support :-)

Also, readme still states netstandard 1.6 instead of 2.0

**Comment by roy-t** [comment]
Oops, I'll fix that over the weekend. No problem. Hope it solves your issues!
________________________________
